# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "{{PROJECT_SLUG}}"

  config.vm.define "{{PROJECT_SLUG}}-linux-build-machine" do |tm|
    tm.vm.provider "virtualbox" do |v, override|
      override.vm.box = "ubuntu/trusty64"
      v.memory = 512
      v.cpus = 1
    end

    tm.vm.network "private_network", ip: "192.168.51.7"

    tm.vm.synced_folder ".", "/go/src/{{IMPORT_PATH}}"
    tm.vm.synced_folder "/tmp", "/tmp"

    tm.vm.provision "shell", run: "always", path: "./scripts/vagrant/bootstrap.sh"
  end
end
