#!/bin/bash
if [ ! -d ./.git ]; then
    echo "You must push your project from the root, so the hooks run properly. Exiting."
    exit 1
fi
    
files_modified=`git diff-index --name-only HEAD`
    
touched_python_files=`git diff --cached --name-only |egrep '\.py$' || true`
if [ -n "$touched_python_files" ]; then
    # Disable this because it's causing merge issues
    #autopep8 \
        #--in-place \
        #--jobs=0 \
        #--max-line-length=120 \
        #$touched_python_files

    #docformatter \
        #--in-place \
        #--wrap-summaries 120 \
        #--wrap-descriptions 120 \
        #$touched_python_files

    #git diff --cached --name-only |egrep '\.py$' |  xargs -l git add

    pylint $touched_python_files
	if [ $? != 0 ]; then
		echo "Code fails pylint check."
		exit 1
	fi
fi
exit 0
