#!/bin/sh -e
# Script to update dns (freedns.afraid.org)

if [ -z "$1" ]; then
    echo "$0: called with no interface" 1>&2
    exit 1;
fi

IF=$1
STATUS=$2

if [ "$IF" = "wlan0" ] && [ "$STATUS" = "up" ]; then
    echo "Updating FreeDNS @ `date`" >> $HOME/var/log/dns-update.log
    echo "REPLACE THIS WITH THE PROPER URL!"
    wget -O - -q --read-timeout=0.0 --waitretry=5 --tries=400 http://freedns.afraid.org/dynamic/update.php?{{key}} >> $HOME/var/log/dns-update.log
    echo "DNS Update Finished @ `date`" >> $HOME/var/log/dns-update.log
fi
