#!/bin/sh
function ocr() {
  local img
  img="$(mktemp)"

  local out
  out="$(mktemp)"
  screencapture -i "${img}"
  #/usr/local/bin/mogrify -modulate 100,0 -resize 400% "${img}" 
  /usr/local/bin/tesseract -l eng --psm 3 "${img}" "${out}"
  cat "${out}.txt"
}

ocr
