#!/bin/bash
if [ ! -d ./.git ]; then
    echo "You must push your project from the root, so the hooks run properly. Exiting."
    exit 1
fi
    
touched_js_files=`git diff --cached --name-only |egrep '\.js$' || true`
if [ -n "$touched_js_files" ]; then
	eslint -c ./eslintrc.json $touched_js_files
	if [ $? != 0 ]; then
		echo "Code fails eslint check."
		exit 1
	fi
fi
exit 0
