#!/bin/sh

if [ -e ".gopath" ]
then
    path="./`cat .gopath`"
else
    path="./_gopath"
fi
path=`realpath $path`

if [ ! -d path ]
then
    read -p "GOPATH $path not found.  Create? " -n 1 -r
    echo #newline
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        mkdir $path
        echo "GOPATH $path created"
    else
        echo "Cannot continue without gopath. Exiting."
        exit
    fi
else
    echo "GOPATH $path found"
fi

export GOPATH=$path
echo $GOPATH
